services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
